CREATE TABLE Courses
(
	CourseID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	CourseName NVARCHAR(250) NOT NULL
)

--INSERT INTO Courses VALUES(NEWID(), 'AZ-900')
--INSERT INTO Courses VALUES(NEWID(), 'PSC')


CREATE TABLE Users
(
	UserID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserName NVARCHAR(250) NOT NULL,
	UserPassword   NVARCHAR(500)
)
